substitutions:
  friendly_name: Microfire Mod-CHRG
  device_name: microfire-mod-chrg-espnow
esphome:
  name: $device_name
esp32:
  board: esp32dev
  framework:
    type: arduino
logger:

globals:
  - id: sent
    type: int
    restore_value: no
    initial_value: '0'

now_mqtt:
  on_sent:
    then:
      - lambda: id(sent)++; 
      - if:
          condition:
            lambda: 'return id(sent) == 13;'
          then:
            - lambda: id(sent) = 0;
            - deep_sleep.enter:
                id: sleep_
                sleep_duration: 5min

deep_sleep:
  id: sleep_
  
# import the component
external_components:
  - source:
      type: local
      path: ./esphome/components/

# https://esphome.io/components/i2c.html
i2c:
  sda: 21
  scl: 22
  scan: true

sensor:
  - platform: mod_chrg
    id: chrg
    update_interval: 10s
    state:
      name: Charge state
    battery_temperature:
      name: Battery temperature
    battery_voltage:
      name: Battery Voltage
    system_voltage:
      name: System Voltage
    bus_voltage:
      name: Bus Voltage
    input_voltage:
      name: VPMID Voltage
    battery_current:
      name: Battery Current
    bus_current:
      name: Bus Current
    die_temperature:
      name: Die Temperature
    bus_fault:
      name: Bus voltage Fault
    battery_fault:
      name: Battery Fault
    system_fault:
      name: System Fault
    thermal_shutdown:
      name: Thermal Shutdown