esphome:
  name: now-eth-mqtt-bridge
esp32:
  board: esp32dev
  variant: esp32
  framework:
    type: arduino
logger:

# import the components
external_components:
  - source:
      type: local
      path: esphome/components

# ESP-Now bridge works concurrently
now_mqtt_bridge:

# wifi:
#   ssid: !secret wifi_ssid
#   password: !secret wifi_password

ethernet:
  type: LAN8720
  mdc_pin: GPIO23
  mdio_pin: GPIO18
  clk_mode: GPIO0_IN
  phy_addr: 1
  power_pin: GPIO16

mqtt:
  id: mqtt_broker
  broker: !secret mqtt_broker
  username: !secret mqtt_username
  password: !secret mqtt_password

